import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { createSupabaseServerClient } from '@/lib/supabase-server'

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
})

// POST /api/resolutions
// Accepts a topic area and returns 5 balanced debate resolutions generated by Claude.
// Only accessible to logged-in users.
export async function POST(request: Request) {
  // Verify the user is logged in before calling the AI
  const supabase = await createSupabaseServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { topicArea } = await request.json()
  if (!topicArea) return NextResponse.json({ error: 'Missing topicArea' }, { status: 400 })

  const message = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 1024,
    messages: [
      {
        role: 'user',
        content: `Generate exactly 5 debate resolutions for the topic area: "${topicArea}".

Requirements:
- Each resolution must be a clear, specific, debatable statement (not a question)
- Both sides must have a legitimate, reasonable argument — avoid one-sided statements
- Make them current and relevant to recent events or ongoing debates
- Keep each resolution to one sentence
- Format: return ONLY a JSON array of 5 strings, no explanation

Example format: ["Resolution one", "Resolution two", "Resolution three", "Resolution four", "Resolution five"]`,
      },
    ],
  })

  // Extract the text response from Claude
  const content = message.content[0]
  if (content.type !== 'text') {
    return NextResponse.json({ error: 'Unexpected response from Claude' }, { status: 500 })
  }

  // Parse the JSON array Claude returned
  const resolutions: string[] = JSON.parse(content.text)
  return NextResponse.json({ resolutions })
}
